Web/Areas/Admin/ViewModels/OurVision/OurVisionCreateVM.cs
namespace WebApp.ViewModels.OurVision
{
    public class OurVisionCreateVM
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public IFormFile Photo { get; set; }
    }
}

Web/Areas/Admin/ViewModels/OurVision/OurVisionIndexVM.cs
namespace WebApp.ViewModels.OurVision
{
    public class OurVisionIndexVM
    {
        public List<Core.Entities.OurVision> OurVisions { get; set; }
    }
}

Web/Areas/Admin/ViewModels/OurVision/OurVisionUpdateVM.cs
namespace WebApp.ViewModels.OurVision
{
    public class OurVisionUpdateVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public IFormFile? Photo { get; set; }
        public string? PhotoName { get; set; }
    }
}

Web/Areas/Admin/Controllers/OurVisionController.cs
using Core.Utilities;
using Microsoft.AspNetCore.Mvc;
using WebApp.Services.Abstract;

using WebApp.ViewModels.HomeMainSlider;
using WebApp.ViewModels.OurVision;

namespace WebApp.Controllers
{
    [Area("Admin")]
    public class OurVisionController : Controller
    {
        private readonly IOurVisionService _visionService;
        private readonly IFileService _fileService;

        public OurVisionController(IOurVisionService visionService, IFileService fileService)
        {
            _visionService = visionService;
            _fileService = fileService;
        }
        #region index
        public async Task<IActionResult> Index()
        {
            var model = await _visionService.GetAllAsync();
            return View(model);
        }
        #endregion
        #region create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(OurVisionCreateVM model)
        {
            var isSucceeded = await _visionService.CreateAsync(model);
            if (isSucceeded) return RedirectToAction(nameof(Index));
            return View(model);
        }
        #endregion
        #region Update
        [HttpGet]

        public async Task<IActionResult> Update(int id)
        {
            var model = await _visionService.GetUpdateModelAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, OurVisionUpdateVM model)
        {

            if (id != model.Id) return NotFound();
            var isSucceeded = await _visionService.UpdateAsync(model);
            if (isSucceeded) return RedirectToAction(nameof(Index));
            return View(model);
        }
        #endregion
        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _visionService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));

        }
        #endregion

    }
}

Web/Areas/Admin/Views/OurVision/Create.cshtml
@using Core.Constants
@using WebApp.ViewModels.OurVision
@model OurVisionCreateVM

<div class="main-panel">

    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <p class="card-description">
Our Vision
</p>
                        <form enctype="multipart/form-data" method="post" asp-action="create" asp-controller="ourvision" class="forms-sample">
                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input class="form-control" asp-for="Title">
                                <span asp-validation-for="Title"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input class="form-control" asp-for="Description">
                                <span asp-validation-for="Description"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input class="form-control" asp-for="Photo">
                                <span asp-validation-for="Photo"></span>
                            </div>

                           


                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <a class="btn btn-danger" asp-action="index" asp-controller="ourvision"> Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/OurVision/Index.cshtml
@using WebApp.ViewModels.OurVision
@model OurVisionIndexVM

<a class="btn btn-warning" asp-action="create" asp-controller="OurVision">Create</a>
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
       
            <th scope="col">Photo</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var vision in Model.OurVisions)
        {

            <tr>
                <td>@vision.Id</td>
                <td>@vision.Title</td>
                <td>@vision.Description</td>
               
                <td><img style="width:70px;height:70px; border-radius:50%" src="~/assets/images/@vision.Photo" />
                <td>
                <td>
                    <form asp-route-id="@vision.Id" method="get" asp-action="delete" asp-controller="OurVision">
                        <input id="id" name="id" value="@vision.Id" type="hidden" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                    <a class="btn btn-primary" asp-action="update" asp-controller="OurVision" asp-route-id="@vision.Id">Update</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Web/Areas/Admin/Views/OurVision/Update.cshtml
@using Core.Constants
@using WebApp.ViewModels.OurVision
@model OurVisionUpdateVM

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <p class="card-description">
                         Our  Vision
                        </p>
                        <form enctype="multipart/form-data" method="post" asp-action="update" asp-controller="ourvision" class="forms-sample">
                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input class="form-control" asp-for="Title">
                                <span asp-validation-for="Title"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description">Description</label>
                                <input class="form-control" asp-for="Description">
                                <span asp-validation-for="Description"></span>
                            </div>
                        
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input class="form-control" asp-for="Photo">
                                <span asp-validation-for="Photo"></span>
                            </div>
                           
                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <a class="btn btn-danger" asp-action="index" asp-controller="ourvision"> Cancel</a>
                        </form>
            

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>